Importing the dependencies

In [4]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [6]:
#loading the data from the csv file to a pandas dataframe
movies_data=pd.read_csv('movies.csv', engine='python', on_bad_lines='skip')

In [ ]:
#printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [7]:
#number of rows and columns
movies_data.shape

(197, 24)

In [8]:
#selecting the relevant features for recommendation
selected_features=['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [9]:
#replacing the null values with null string
for feature in selected_features:
  movies_data[feature]=movies_data[feature].fillna('')

In [10]:
#combining all the 5 selected features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [11]:
print(combined_features)

0      Action Adventure Fantasy Science Fiction cultu...
1      Adventure Fantasy Action ocean drug abuse exot...
2      Action Adventure Crime spy based on novel secr...
3      Action Crime Drama Thriller dc comics crime fi...
4      Action Adventure Science Fiction based on nove...
                             ...                        
192    Drama missionary world war ii ranch australia ...
193    Science Fiction Action Adventure dystopia Dang...
194    Animation Family cataclysm asteroid leader com...
195    Adventure Comedy Fantasy Family night watchman...
196    Animation Action Comedy Family Science Fiction...
Length: 197, dtype: object


In [12]:
#converting the text data to feature vectors
vectorizer=TfidfVectorizer()

In [13]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [14]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5466 stored elements and shape (197, 2146)>
  Coords	Values
  (0, 11)	0.06064200715835276
  (0, 20)	0.0533330565414193
  (0, 649)	0.08732369266234423
  (0, 1698)	0.08545978200087222
  (0, 671)	0.08545978200087222
  (0, 440)	0.2311326004736821
  (0, 369)	0.2311326004736821
  (0, 734)	0.16899964723189875
  (0, 1792)	0.31423118679266726
  (0, 2029)	0.1478976051001678
  (0, 381)	0.214382967338276
  (0, 1777)	0.2311326004736821
  (0, 610)	0.2311326004736821
  (0, 1892)	0.0762417937047064
  (0, 2109)	0.12066438031924331
  (0, 1393)	0.1140934689718434
  (0, 1440)	0.2311326004736821
  (0, 1671)	0.14523153956076856
  (0, 2112)	0.20249891350271093
  (0, 2141)	0.19328092520654505
  (0, 1667)	0.19328092520654505
  (0, 1753)	0.2311326004736821
  (0, 2049)	0.2311326004736821
  (0, 1814)	0.214382967338276
  (0, 1094)	0.2311326004736821
  :	:
  (196, 915)	0.16293423341390673
  (196, 1921)	0.1378959801346719
  (196, 77)	0.10583711177360426
 

In [15]:
#cosine similarity
#getting the similarity scores using cosine similarity
similarity=cosine_similarity(feature_vectors)

In [16]:
print(similarity)

[[1.         0.06532771 0.02965828 ... 0.         0.01472888 0.04508518]
 [0.06532771 1.         0.02848506 ... 0.         0.04083606 0.04688927]
 [0.02965828 0.02848506 1.         ... 0.03148589 0.02325535 0.02478105]
 ...
 [0.         0.         0.03148589 ... 1.         0.00709736 0.02938414]
 [0.01472888 0.04083606 0.02325535 ... 0.00709736 1.         0.02886307]
 [0.04508518 0.04688927 0.02478105 ... 0.02938414 0.02886307 1.        ]]


In [17]:
print(similarity.shape)

(197, 197)


In [18]:
#getting the movie name from the user
movie_name=input('enter your favourite movie name:')

enter your favourite movie name:avatar


In [19]:
#creating a list with all the movie names given in the dataset
list_of_all_titles=movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [20]:
#finding the close match for the movie name given by user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Avatar']


In [21]:
close_match=find_close_match[0]
print(close_match)

Avatar


In [22]:
#finding  the index of the movie with title
index_of_the_movie=movies_data[movies_data.title==close_match]['index'].values[0]
print(index_of_the_movie)

0


In [23]:
#getting a list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(1.0000000000000002)), (1, np.float64(0.06532770518836901)), (2, np.float64(0.02965827762649851)), (3, np.float64(0.010459881514011268)), (4, np.float64(0.07985450434753637)), (5, np.float64(0.0773618751583438)), (6, np.float64(0.002910392973553355)), (7, np.float64(0.02351411665392336)), (8, np.float64(0.0262811241528657)), (9, np.float64(0.014662303432177441)), (10, np.float64(0.07950211177110442)), (11, np.float64(0.00560796507039785)), (12, np.float64(0.015135981276509801)), (13, np.float64(0.02961268430244396)), (14, np.float64(0.04961259519045537)), (15, np.float64(0.010433541396510575)), (16, np.float64(0.02267723215093256)), (17, np.float64(0.013891801855313718)), (18, np.float64(0.04805344617945524)), (19, np.float64(0.036161318611722344)), (20, np.float64(0.03379080055310406)), (21, np.float64(0.005471899390698456)), (22, np.float64(0.028347632102451788)), (23, np.float64(0.037761004899756256)), (24, np.float64(0.03728447563002699)), (25, np.float64(0.055656270

In [24]:
len(similarity_score)

197

In [25]:
#sorting the movies based on their similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(0, np.float64(1.0000000000000002)), (94, np.float64(0.21851427870081822)), (56, np.float64(0.17515021007453765)), (47, np.float64(0.17426760181064885)), (158, np.float64(0.11775275379633753)), (43, np.float64(0.11286739165405753)), (108, np.float64(0.10356795753582583)), (44, np.float64(0.10185554712626192)), (156, np.float64(0.09098102340944675)), (46, np.float64(0.08949410630327222)), (37, np.float64(0.088353176078919)), (150, np.float64(0.08743337546061383)), (30, np.float64(0.08199809652036369)), (4, np.float64(0.07985450434753637)), (10, np.float64(0.07950211177110442)), (184, np.float64(0.0794143108732739)), (61, np.float64(0.07934386395702711)), (5, np.float64(0.0773618751583438)), (99, np.float64(0.07392131909450572)), (132, np.float64(0.07111323961489409)), (26, np.float64(0.06979871058924045)), (82, np.float64(0.06569725492538421)), (101, np.float64(0.06555663678845938)), (1, np.float64(0.06532770518836901)), (76, np.float64(0.06485975037366236)), (111, np.float64(0.0641655

In [26]:
#print the name of similar movies based on the index
print('movies suggested for you:')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<40):
    print(i,'.',title_from_index)
    i=i+1

movies suggested for you:
1 . Avatar
2 . Guardians of the Galaxy
3 . Star Trek Beyond
4 . Star Trek Into Darkness
5 . Star Trek
6 . Terminator Salvation
7 . Terminator Genisys
8 . Furious 7
9 . The Last Samurai
10 . X-Men: Days of Future Past
11 . Oz: The Great and Powerful
12 . Men in Black II
13 . Spider-Man 2
14 . John Carter
15 . Superman Returns
16 . Home
17 . Jupiter Ascending
18 . Spider-Man 3
19 . The Fast and the Furious
20 . Wrath of the Titans
21 . Captain America: Civil War
22 . Dawn of the Planet of the Apes
23 . X-Men: First Class
24 . Pirates of the Caribbean: At World's End
25 . G.I. Joe: The Rise of Cobra
26 . Transformers
27 . G-Force
28 . Shrek the Third
29 . Captain America: The First Avenger
30 . Spider-Man
31 . Captain America: The Winter Soldier
32 . Inception
33 . Titanic
34 . Iron Man 3
35 . Mad Max: Fury Road
36 . Dark Shadows
37 . 2012
38 . Noah
39 . Die Another Day


Movie Recommendation system

In [27]:

movie_name=input('enter your favourite movie name:')
list_of_all_titles=movies_data['title'].tolist()
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
index_of_the_movie=movies_data[movies_data.title==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print('movies suggested for you:\n')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<40):
    print(i,'.',title_from_index)
    i=i+1



enter your favourite movie name:spiderman
movies suggested for you:

1 . Spider-Man
2 . Spider-Man 2
3 . Spider-Man 3
4 . Oz: The Great and Powerful
5 . Hancock
6 . Harry Potter and the Order of the Phoenix
7 . Inception
8 . John Carter
9 . The Great Gatsby
10 . Avatar
11 . The Amazing Spider-Man
12 . Poseidon
13 . Harry Potter and the Prisoner of Azkaban
14 . The Hunger Games: Catching Fire
15 . Tomorrowland
16 . Iron Man 3
17 . The Last Samurai
18 . Turbo
19 . The Good Dinosaur
20 . The Wolfman
21 . G-Force
22 . Superman Returns
23 . Maleficent
24 . Pirates of the Caribbean: At World's End
25 . Snow White and the Huntsman
26 . X-Men: Days of Future Past
27 . Master and Commander: The Far Side of the World
28 . Stealth
29 . Alice Through the Looking Glass
30 . Spectre
31 . Hulk
32 . Terminator Salvation
33 . Skyfall
34 . The Golden Compass
35 . X-Men: First Class
36 . Furious 7
37 . Sahara
38 . Guardians of the Galaxy
39 . Harry Potter and the Half-Blood Prince
